# version: 2.1

# orbs:
#   node: circleci/node@5.0.2
  
# # heroku orb for auto deploy
#   heroku: circleci/heroku@1.2.6

# # Define a job to be invoked later in a workflow.
# # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# jobs:
#   run_tests:
#     docker:
#       - image: cimg/node:18.9.0
    
#     steps:
#     - checkout
#     - restore_cache:
#         key: dependency-cache-{{ checksum "package.json" }}
#     - run:
#         name: Install dependacies
#         command: npm install
#     - save_cache:
#         key: dependency-cache-{{ checksum "package.json" }}
#         paths:
#           - ./node_modules
#     - run:
#         name: Run test
#         command: npm test
 
# workflows:
#   run-tests-workflow:
#     jobs:
#       - run_tests
#       - heroku/deploy-via-git:
#           requires:
#             - run_tests
#           filters:
#             branches:
#               only: main
      


    

version: 2.1
orbs:
  node: circleci/node@5.0.2

  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build
      
      - heroku/deploy-via-git: 

          requires:
          
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    docker:
      - image: cimg/node:18.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command: npm test



  


